### ISSUE TITLE
都没涵交作业的吗（bushi

### ISSUE THREAD

**Issue by yhx-12243** [Btlmd/sast2022-crawler-SQL-training#1]
https://git.tsinghua.edu.cn/yu-hx21/sast2022-crawler-SQL-training

**Comment by KujoStar** [comment]
我交在了一个诡异的位置（什么

**Comment by Btlmd** [comment]
- Zhihu
  - 实现合理
  - 看起来您 `python` 掌握十分熟练 Orz
  - fake-useragent 也很好
- WebVPN
  - 实现合理
  - 使用参数或询问而不是配置文件的方式读入用户名与密码，设计比我合理
  - 不仅恰当地地运用了 `argparse` ，方法的级联更是十分优雅。
- SQL 
  - 查询正确
  - （虽然我个人感觉 `ignore` 总还是心理不很踏实，但这个实现完全没问题
- 代码风格优雅，docstring 完备，`property`, `staticmethod` 等 python 语言特性使用得当，README 清晰易懂。

最后，感谢找出了我作业中的许多 bug ！
