### ISSUE TITLE
Homowork submit

### ISSUE THREAD

**Issue by KujoStar** [Btlmd/sast2022-crawler-SQL-training#10]
https://git.tsinghua.edu.cn/cmh21/sast2022-crawler-SQL-training

**Comment by Btlmd** [comment]
- 知乎爬虫

  - 实现合理
  - 你的 Cookie 是否已经保证失效？否则有账号危险

- WebVPN

  - 实现合理

  - ```python
    res[x]=round(total_GPA/total_weight,2) # 是否考虑在等号和函数参数处加空格
    res[x] = round(total_GPA / total_weight, 2)
    ```

  - 用 `\n` 提交，Nice！

  - 没有用 `webdriver_manager` ? \doge

- SQL

  - 查询正确

- 代码风格

  - 是否考虑使用比 `iii`, `fff`, `ggg` 更有意义的变量名称？
  - 涵涵啊代码格式化一下呜呜
  - 不建议将异常捕获之后抛出一个与原先无关的异常，因为会损失许多信息
