### ISSUE TITLE
Homework Submit

### ISSUE THREAD

**Issue by Sweetlemon68** [Btlmd/sast2022-crawler-SQL-training#12]
[SAST2022-crawler-SQL-training](https://git.tsinghua.edu.cn/mrj21/sast2022-crawler-sql-training)

#### requests 部分

- 环境配置：使用 Python 3.8，在 `Zhihu_crawler` 目录下运行 `pip3 install -r requirements.txt` 安装依赖。
- 使用方法：在 `Zhihu_crawler/zhihu.json` 中按提示填入 MySQL 服务器 IP、端口、账号、密码、数据库名称等信息，再运行 `python3 zhihu.py` 即可，程序会每 10 分钟自动爬取一次。
- 样例数据：见 `Zhihu_crawler/zhihu_crawler_export.sql`。

#### Selenium 部分

- 环境配置：使用 Python 3.8，在 `WebVPN_crawler` 目录下运行 `pip3 install -r requirements.txt` 安装依赖。本作业使用的是 Firefox 浏览器，请确认计算机中安装有此浏览器（否则可尝试将脚本中的 `firefox`、`gecko` 等改为对应大小写的 `chrome`）。
- 使用方法：在 `WebVPN_crawler/settings.json` 中按提示填入清华学号和 INFO 账号密码，再运行 `python3 webvpn.py` 即可，程序运行完毕后会输出各学期 GPA 和总 GPA。注意：若您的 Firefox 是 Snap 安装的（如 Ubuntu 22.04 LTS 中预装的 Firefox），请先在同一终端中运行 `mkdir $HOME/tmp; export TMPDIR=$HOME/tmp geckodriver`，再运行脚本。

#### SQL 部分

七条命令见 `SQL_query/my_answer.sql`，完整日志见 `SQL_query/my_out.log`。

**Comment by Btlmd** [comment]
- 知乎爬虫
  - 实现合理
- WebVPN
  - 实现合理
- SQL
  - 查询正确
- 代码风格
  - 提交说明十分详尽，Orz！
  - 代码简洁优雅！
