### ISSUE TITLE
Homework submit

### ISSUE THREAD

**Issue by Kevin-thu** [Btlmd/sast2022-crawler-SQL-training#13]
https://github.com/KevinTHU2003/sast2022-crawler-SQL-training

**Comment by Btlmd** [comment]
- 知乎爬虫
  - 实现合理
- WebVPN
  - 实现合理
- SQL
  - 没有提交 Q5，Q6 ？
  - 其余查询正确
- 代码风格
  - 通常 python 代码推荐使用小写 + 下划线的方式为函数和变量命名，参见 https://peps.python.org/pep-0008/#function-and-variable-names
  - README 简洁清晰
