### ISSUE TITLE
Homework submission

### ISSUE THREAD

**Issue by srzer** [Btlmd/sast2022-crawler-SQL-training#14]
https://git.tsinghua.edu.cn/srz21/crawler-and-sql

**Comment by Btlmd** [comment]
- 知乎爬虫

  - 对于这部分内容

    ```python
    divs_title=soup.find_all(class_="HotList-itemTitle")
    divs_re=soup.find_all(class_="HotList-itemMetrics")
    divs_excerpt=re.findall(r'excerptArea":{"text":"([^{}]*)"},"imageArea"',resp.text)
    divs_id=re.findall(r'Q_([0-9]*)',resp.text)
    ```

    实现时没有判断 `re.findall`, `soup.findall` 得到的 4 个数组的长度是否相同。这可能导致遇到匹配数量不同时，问题的 `id`, `excerpt` 等失配

  - 为啥只爬前 40 呐 \doge
  - 虽然正则表达式解析也可以完成本题，但个人认为还是解析 JSON 会更加鲁棒

- WebVPN

  - 实现合理

- SQL

  - 查询正确

- 代码风格

  - 是否考虑在运算符前后加空格？如这样

    ```python
    now_credit = int(divs[now_row + 2].text)
    ```
