### ISSUE TITLE
Homework Submission

### ISSUE THREAD

**Issue by Hanyx2021** [Btlmd/sast2022-crawler-SQL-training#18]
https://git.tsinghua.edu.cn/hanyx21/hw2

**Comment by Btlmd** [comment]
- 知乎爬虫

  - 实现合理

- WebVPN

  - 实现本身没有问题，但

    ```python
    gpa = {'2020-秋':0,'2021-春':0,'2021-夏':0,'2021-秋':0,'2022-春':0}
    ```

    这种信息可能更应该从页面中爬取而不是硬编码在这里，比如九字班学长来了可能就会有 `KeyError`

- SQL
  - 查询正确

- 代码风格
  - 实现之后可以考虑将 `raise NotImplementedError` 和 `TODO `删 去，毕竟您已经实现了功能（当然这点是非本质的）
