### ISSUE TITLE
homework

### ISSUE THREAD

**Issue by lv-zy** [Btlmd/sast2022-crawler-SQL-training#19]
https://github.com/lv-zy/sast2022-crawler-SQL-training
2021010833

**Comment by Btlmd** [comment]
- 知乎爬虫

  - 实现合理
  - `logger` 运用合理

- WebVPN

  -  模拟用户操作的部分实现合理
  -  但处理 HTML 时可能存在一些不鲁棒的情形。在我这里运行时，显示到成绩单界面都一切正常，但将 Window 关闭后进行数据处理的过程中会发生

    ```python
    Traceback (most recent call last):
      File "webvpn.py", line 246, in <module>
        wb.get_grades()
      File "webvpn.py", line 170, in get_grades
        self.parse_grade(content)
      File "webvpn.py", line 208, in parse_grade
        seme = td_list[5].string
    IndexError: list index out of range
    ```

- SQL
  - Q7 没有按照 `qid` 排升序，其余没有问题

- 代码风格
  - 整体上来说代码简洁优雅
  - 实现之后可以考虑将 `raise NotImplementedError` 和 `TODO `删 去，毕竟您已经实现了功能（当然这是非本质的）
