### ISSUE TITLE
Homework submit

### ISSUE THREAD

**Issue by tjq21** [Btlmd/sast2022-crawler-SQL-training#2]
https://git.tsinghua.edu.cn/tjq21/crawler_sql_exercise

**Comment by Btlmd** [comment]
- 知乎爬虫

  -  API 选择很巧妙啊，直接 JSON 了
  - `argparse` 运用也很恰当

- WebVPN

  - 考虑了用户名和密码错误情形十分 Nice！不过出错了之后使用 `ValueError` 可能比 `NotImplementedError` 更恰当，错误的信息也可以附在异常类中而不用 `print` ，如

    ```python
    if(d.find_element(By.ID, "error-message")):
    	raise ValueError("用户名或密码错误！")
    ```

  - 同理还有后面的类似代码，如果想要记录异常后继续抛出，可能

    ```python
    except Exception as e:
        # something to log
        raise
    ```

    会比使用 `NotImplementedError` 更加合适 

- SQL 查询没问题 :)

- 代码风格良好，README 详细且易读
