### ISSUE TITLE
homework

### ISSUE THREAD

**Issue by anxieter** [Btlmd/sast2022-crawler-SQL-training#20]
https://github.com/anxieter/summer-training/tree/submission
2021010781

**Comment by Btlmd** [comment]
- 知乎爬虫

  - 实现合理

- WebVPN

  - 模拟用户访问和点击的部分很棒

  - 处理成绩点时边界条件的鲁棒性稍有瑕疵

    - 例如没有处理退课 W 的情况，导致退过课的使用者得到了

      ```python
      Traceback (most recent call last):
        File "webvpn.py", line 197, in <module>
          f.write(str(web.get_grades()))
        File "webvpn.py", line 163, in get_grades
          result[sem].append((int(k[2]),float(k[4])))
      ValueError: could not convert string to float: 'N/A'
      ```

    - 并不是所有的 F 都不算 GPA
    - 在这里使用 `N/A` 来判断绩点计算可能更加合理

- SQL

  - 查询正确

- 代码风格

  - 在算符前后加上空格可能会令代码更加易读
