### ISSUE TITLE
hw2

### ISSUE THREAD

**Issue by wang-hd21** [Btlmd/sast2022-crawler-SQL-training#21]
我想爬了

**Comment by wang-hd21** [comment]
https://github.com/wang-hd21/crawler_sql_hw

**Comment by Btlmd** [comment]
- 知乎爬虫
  - 实现简洁合理 Orz！
- WebVPN
  - (仅适用于一字班233333
  - 实现合理！
- SQL 
  - 查询正确
- 代码风格
  - Pythonic ！
