### ISSUE TITLE
hw2

### ISSUE THREAD

**Issue by Qinyu-Xu** [Btlmd/sast2022-crawler-SQL-training#22]
https://git.tsinghua.edu.cn/xqy21/sast2022homework2

**Comment by Btlmd** [comment]
- 知乎爬虫
  - 实现合理
  - 解析简洁优雅
  - （确实有广告 😺 
- WebVPN
  - 实现合理
  - 代码都写好了，就多考虑几个学期呗，这个实现在学期多起来的时候会把所有春季学期 & 所有秋季学期拿出来算绩点 😢 
- SQL
  - 查询正确
- 代码风格
  - 优雅！
