### ISSUE TITLE
Homework Submission

### ISSUE THREAD

**Issue by abmfy** [Btlmd/sast2022-crawler-SQL-training#23]
https://git.tsinghua.edu.cn/wangbw21/sast2022-crawler-SQL-training

**Comment by Btlmd** [comment]
- 知乎爬虫
  - 实现合理
  - 鲁棒、简洁、优雅、Orz！
- WebVPN
  - 实现合理 
- SQL
  - 查询正确
- 代码风格
  - README 简洁清晰
  - Pythonic！优雅！
