### ISSUE TITLE
hw2

### ISSUE THREAD

**Issue by xinghb21** [Btlmd/sast2022-crawler-SQL-training#24]
https://git.tsinghua.edu.cn/xinghb21/sast2022-hw2.git
2021010823

**Comment by Btlmd** [comment]
- 知乎爬虫
  - 请确认 zhihu.json 中的 Cookie 是否失效，没有失效可能有知乎账号风险
  - 忘记附上爬取的数据库了 ? \doge
  - 在我本地运行有些问题，不过实现思路是合理的，可能使用更加鲁棒的索引方式会更好
- WebVPN
  - 整体实现与模拟点击的思路没什么问题
  - 切换标签页时可能有 bug ，导致切换到错误的标签页
- SQL
  - 查询正确
- 代码风格
  - 可以试着让代码再 Pythonic 一些，例如
    ```python
    k = 0
    for j in i.stripped_strings:
        if k == 2:
            points = float(j)
        if k == 4:
            grades = j
        if k == 5:
            semester = j
        k += 1
    ```
    用下标直接索引或者用 enumerate 来做会更好

    再如判断 `None` 应该用 `is None` 或者 用 `is not None` 而不是从 typing  中引用

   - 一些代码的表述方法令人有点费解
      ```python
      for i in answer[0].strings:
        answerCount = i
        break
      ```

总体来说思路合理，但实现的鲁棒性可以更好 ~
