### ISSUE TITLE
Homework

### ISSUE THREAD

**Issue by IridescentPig** [Btlmd/sast2022-crawler-SQL-training#25]
https://github.com/IridescentPig/sast2022-crawler-SQL-training

**Comment by IridescentPig** [comment]
2021010843

**Comment by Btlmd** [comment]
- 知乎爬虫
  - 实现合理，简洁！
- WebVPN
  -  实现合理，鲁棒！
- SQL
  - 查询正确
- 代码风格
  - 简洁优雅，很 Nice ~
