### ISSUE TITLE
hw2

### ISSUE THREAD

**Issue by foreverpiano** [Btlmd/sast2022-crawler-SQL-training#26]
https://git.tsinghua.edu.cn/dhl21/summer-hw2

**Comment by Btlmd** [comment]
- 知乎爬虫
  - 实现合理、简洁！
  - 忘记附上爬到的数据？\doge
- WebVPN
  - 实现合理
  - 运行时输入用户名 / 密码非常合理
- SQL
  - 查询正确
- 代码风格
  - 优雅易读！！
