### ISSUE TITLE
homework

### ISSUE THREAD

**Issue by endazhao** [Btlmd/sast2022-crawler-SQL-training#28]
https://git.tsinghua.edu.cn/zed21/crawl_sql/-/tree/master/

**Comment by Btlmd** [comment]
- 知乎爬虫
  - 实现合理
  - 似乎忘了附上爬到的数据 😹 

- WebVPN
  - 实现总体合理
  - 部分实现细节不够鲁棒，如
    - 登录 info 时使用 implicit_wait(5) 在我这边有时会因等待时间比较短而会无法登录，可能还是使用 WebDriverWait().until 会更鲁棒
    - 成绩单查询这部分只查出了我 
      ```
      2020-秋: *.**
      2021-春: *.**
      ```
      这两学期的成绩 😢 
- SQL
  - 查询正确
  - 缺少了 2 个问题，不过看起来它们对你来说太容易了 

- 代码风格
  - 总体优雅
  - 在代码中嵌入了绝对路径 😿 
  - 使用 with 进行上下文管理打开文件，无需手动 close
  - 最后的 `raise NotImplementedError` 没删除，这导致程序正常运行结束后抛出一个异常，看着略有难受
