### ISSUE TITLE
Homework Submit

### ISSUE THREAD

**Issue by Xial-kotori** [Btlmd/sast2022-crawler-SQL-training#7]
https://git.tsinghua.edu.cn/yuancf21/hw2-crawler-sql

**Comment by Btlmd** [comment]
- 知乎爬虫
  - 实现合理
  - 不过如果有个 README 说明一下你 `zhihu.json` 中使用了哪些 Header 会更好
  - Forget to upload your database?
- WebVPN
  - 实现合理
  - `imp` 可能换用 `immportlib` 会更好。（虽然其实后面应该也没有用上 x
- SQL
  - 查询正确
- 代码风格
  - 实现之后可以考虑将 `raise NotImplementedError` 和 `TODO `删 去，毕竟您已经实现了功能（当然这是非本质的）

**Comment by Xial-kotori** [comment]
在原链接提交了改正后的版本

+ 知乎爬虫
    + 添加了一个 README 说明了使用的 header
    + 上传了 `zhihu.sql`
+ WebVPN
    + 直接把 `import imp` 删了（虽然确实没有用到）
+ 代码风格
    + 把 `raise NotImplementedError` 和 `TODO` 全删了

**Comment by Btlmd** [comment]
Orz! Nice one!!
