### ISSUE TITLE
Homework submit

### ISSUE THREAD

**Issue by CTP314** [Btlmd/sast2022-crawler-SQL-training#9]
[https://git.tsinghua.edu.cn/luch21/sast2022-crawler-sql-training](https://git.tsinghua.edu.cn/luch21/sast2022-crawler-sql-training)

**Comment by Btlmd** [comment]
- 知乎爬虫
  - 实现合理、简洁
  - 273 - 274 行的代码的 `continue` 是否会导致出现盐选问题后，ranking 不正确？
- WebVPN
  - 实现合理
  -  XPATH 定位可能略显复杂，可能用少量的标签就可能达到效果
- SQL 
  - 查询正确
- 代码风格
  - README 清晰完整
  - 实现之后可以考虑将 `raise NotImplementedError` 和 `TODO `删去，毕竟您已经实现了功能（当然这是非本质的）
